---
- name: Change secret
  hosts: localhost
  gather_facts: no
  vars:
    mypass: UkRGJV40NWZld2ZAI2gK
  tasks:     
    - name: Change secret
      kubernetes.core.k8s:
        namespace: openshift-config
        definition:
         apiVersion: v1
         data:
           bindPassword: "{{ mypass }}"
         kind: Secret
         metadata:
           name: ldap-bind-password-2mfpt
        kubeconfig: kubeconfig
