---
- name: Change secret
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Change secret
      kubernetes.core.k8s:
        namespace: amrotesting299822
        definition:
         apiVersion: v1
         data:
           bindPassword: QEMjeiElUSVm
         kind: Secret
         metadata:
           name: my-secret
        kubeconfig: kubeconfig
