---
- name: Change secret
  hosts: localhost
  gather_facts: no
  tasks:
    - name: encode
      shell: echo 'RDF%^$145fewf@#h'| base64
      register: pass_encoded
    - name: Change secret
      kubernetes.core.k8s:
        namespace: openshift-config
        definition:
         apiVersion: v1
         data:
           bindPassword: pass_encoded
         kind: Secret
         metadata:
           name: ldap-bind-password-2mfpt
        kubeconfig: kubeconfig
