---
- name: install collections
  hosts: localhost
  gather_facts: no
  tasks:
    - name: installation
      shell: ansible-galaxy collection install community.okd
    - name: installation
      shell: ansible-galaxy collection list
      register: result  
    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: result
        verbosity: 2
