---
- name: Log in to OpenShift cluster and create namespace
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Log in (obtain access token)
      community.okd.openshift_auth:
        username: amro
        password: amro
      register: openshift_auth_results
    - name: Get a list of all pods from any namespace
      kubernetes.core.k8s_info:
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        kind: Pod
      register: pod_list
