---
- name: reset Ldap 
  hosts: 172.16.20.20
  gather_facts: no
  tasks:
    - name: reset
      community.windows.win_domain_user:
        name: OC-AD-Amro-Test
        password: "{{ ldap_pass }}"


- name: Change secret
  hosts: localhost
  gather_facts: no
  tasks:     
    - name: Change secret
      kubernetes.core.k8s:
        namespace: openshift-config
        definition:
         apiVersion: v1
         data:
           bindPassword: "{{ ldap_pass | b64encode }}"
         kind: Secret
         metadata:
           name: ldap-bind-password-2mfpt
        kubeconfig: OpenShift_Clusters/kubeconfig


- name: Update SystemParameters table in MS SQL
  hosts: 172.16.129.30
  gather_facts: no
  vars:
    server_name: SRVWSQLAppsT01.hqdomain.com\DBSERVERTEST
    database_name: CorporateIBWorkflow
    sql_username: corporate
    sql_password: Mid@2022
  tasks:
    - name: Update Password_Test value
      win_shell: "sqlcmd -S {{ server_name }} -d {{ database_name }} -U {{ sql_username }} -P {{ sql_password }} -Q \"UPDATE SystemParameters SET [Value] = "{{ ldap_pass }}" WHERE [Key] = 'Password_Test'\""
    - name: Update UserName_Test value
      win_shell: "sqlcmd -S {{ server_name }} -d {{ database_name }} -U {{ sql_username }} -P {{ sql_password }} -Q \"UPDATE SystemParameters SET [Value] = 'eprahim' WHERE [Key] = 'UserName_Test'\""


