---
- name: install pip
  hosts: localhost
  gather_facts: no 
  tasks:
    - name: Install bottle python package
      ansible.builtin.pip:
        name:
          - pywinrm
          - urllib3
- name: reset
  hosts: HQDC01.hqdomain.com
  gather_facts: no
  tasks:
    - name: reset
      microsoft.ad.user:
        name: OC-AD-Amro-Test
        password: ouifhh$%172##
