---
- name: Change secret
  hosts: localhost
  gather_facts: no
  vars:
    ldap_pass: RDF%^$145fewf@#h
  tasks:     
    - name: Change secret
      kubernetes.core.k8s:
        namespace: openshift-config
        definition:
         apiVersion: v1
         data:
           bindPassword: "{{ ldap_pass | b64encode }}"
         kind: Secret
         metadata:
           name: ldap-bind-password-2mfpt
        kubeconfig: kubeconfig
