---
- name: Change secret
  hosts: localhost
  gather_facts: no
  tasks:     
    - name: Change secret
      kubernetes.core.k8s:
        namespace: openshift-config
        definition:
         apiVersion: v1
         kind: Secret
         metadata:
           name: amro_sec
