---
- name: Change secret
  hosts: localhost
  gather_facts: no
  tasks:     
    - name: Change secret
      kubernetes.core.k8s:
        namespace: openshift-config
        definition:
         apiVersion: v1
         data:
           MIDDLEWARE_BASIC_AUTH_USERNAME: AMro
         kind: Secret
         metadata:
           name: amro-cm
      kubeconfig: OpenShift_Clusters/kubeconfig
