---
- name: reset
  hosts: 172.16.20.20
  gather_facts: no
  tasks:
    - name: reset
      microsoft.ad.user:
       # name: hqdomain\OC-AD-Amro-Test
        sam_account_name: hqdomain\OC-AD-Amro-Test
        password: ouiEW$%172##gh!cf
        password_expired: no
        state: present
        domain_server: hqdomain.com
