---
- name: reset
  hosts: 172.16.20.20
  gather_facts: no
  tasks:
    - name: reset
      microsoft.ad.user:
        name: OC-AD-Amro-Test
        sam_account_name: OC-AD-Amro-Test
        password: Welcome%$2023d
        state: present
