---
- name: reset
  hosts: 172.16.20.20
  gather_facts: no
  tasks:
    - name: reset
      microsoft.ad.user:
        name: OC-AD-Amro-Test
        update_password: ouiEW$%172##gh!cf
        domain_server: hqdomain.com
        state: present
